### ISSUE TITLE
pty4j crashes java process

### ISSUE THREAD

**Issue by hurricup** [JetBrains/pty4j#145]
```
Faulting application name: java.exe, version: 17.0.10.0, time stamp: 0xeed197b8
Faulting module name: ucrtbase.dll, version: 10.0.19041.3636, time stamp: 0x81cf5d89
Exception code: 0xc0000409
Fault offset: 0x0000000000071208
Faulting process id: 0x69e0
Faulting application start time: 0x01da62836c1799e4
Faulting application path: C:\Users\hurri\.gradle\caches\modules-2\files-2.1\com.jetbrains\jbre\jbr_jcef-17.0.10-windows-x64-b1186.1\extracted\jbr_jcef-17.0.10-windows-x64-b1186.1\bin\java.exe
Faulting module path: C:\Windows\System32\ucrtbase.dll
Report Id: 7a95e483-eedd-499a-bfdb-6703a632b983
Faulting package full name: 
Faulting package-relative application ID: 
```
`IDEA 241.12662.62-EAP-SNAPSHOT`

https://stackoverflow.com/a/49781951

![image](https://github.com/JetBrains/pty4j/assets/2811330/ee30f69d-f251-4a27-843f-fca24f48c7ea)

**Comment by debxrshi** [comment]
How did you fix dependency issue?

**Comment by segrey** [comment]
This issue is reproduced on Windows only.

**Steps to reproduce**
1. Move `pty4j` to a parent directory whose full path length is at least 157 characters (so, the length of `C:\path\...\to\pty4j` is 163 characters or higher).
2. Open the moved `pty4j` and run `gradle test`.

**Expected**: the tests are run correctly
**Actual**: the tests are failed
```
Execution failed for task ':test'.
> Process 'Gradle Test Executor 4' finished with non-zero exit value -1073740791
```
![image](https://github.com/JetBrains/pty4j/assets/607109/ecd68a81-4c2f-4381-af14-2574036caf3c)

Caused by https://github.com/microsoft/terminal/issues/16860

**Comment by segrey** [comment]
Causes [IDEA-347968](https://youtrack.jetbrains.com/issue/IDEA-347968)
