### ISSUE TITLE
How to get current directory?

### ISSUE THREAD

**Issue by Stefman87** [JetBrains/pty4j#154]
Could anyone say how to get current directory? I found that there is a  WinPtyProcess.getWorkingDirectory() method, but it seems that this method exists only for Windows. Could anyone say if there is a cross-platform solution?

**Comment by segrey** [comment]
Unfortunately, `WinPtyProcess#getWorkingDirectory` doesn't work for PowerShell (see the added test). Probably, it will be removed in future. Seems the only reliable way to fetch working directory is to report the working directory through shell integration.

**Comment by segrey** [comment]
@Stefman87 Yes, the code looks similar to https://github.com/JetBrains/pty4j/blob/330e17626a5e54c7d42ce8de2d63902cf6dbbbfb/native/win-helper/win-helper.cpp. Unfortunately, it doesn't work for PowerShell 5.1. I'd say, it's kind of expected, because a shell is not obligated to update current directory in the [PEB](https://learn.microsoft.com/en-us/windows/win32/api/winternl/ns-winternl-peb).

The solution for Unix is not ideal either. The proper solution is to report working directory from inside shell using shell integration.

**Comment by segrey** [comment]
@Stefman87 It's impossible, because pty4j doesn't know that a child process it creates is a shell. Even if it tried to guess it, it's not pty4j's responsibility, because pty4j implements general process launching mechanism. Unfortunately, adding `WinPtyProcess#getWorkingDirectory` / `WinConPtyProcess#getWorkingDirectory` was a mistake in the first place.
